# Generated by Django 4.2.14 on 2024-08-08 21:39

from django.db import migrations, models
import django.db.models.deletion
import store_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=store_service.models.furniture_upload_path,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("CHOICE1", "XS"),
                            ("CHOICE2", "S"),
                            ("CHOICE3", "M"),
                            ("CHOICE3", "L"),
                            ("CHOICE3", "XL"),
                            ("CHOICE3", "XXL"),
                            ("CHOICE3", "3XXL"),
                        ],
                        default="CHOICE3",
                        max_length=32,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store_service.category",
                    ),
                ),
            ],
        ),
    ]
