# Generated by Django 4.2.14 on 2024-08-08 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="color",
            field=models.CharField(
                choices=[
                    ("GREEN", "White"),
                    ("BLUE", "Blue"),
                    ("RED", "Red"),
                    ("SILVER", "Silver"),
                    ("GREY", "Grey"),
                    ("VIOLET", "Violet"),
                    ("BLACK", "Black"),
                ],
                default="GREEN",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="size",
            field=models.CharField(
                choices=[
                    ("CHOICE1", "XS"),
                    ("CHOICE2", "S"),
                    ("CHOICE3", "M"),
                    ("CHOICE3", "L"),
                    ("CHOICE3", "XL"),
                    ("CHOICE3", "XXL"),
                    ("CHOICE3", "3XXL"),
                ],
                default="CHOICE1",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="baskets", to="store_service.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baskets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
