// export * from '../pages/Account/Account.module';
export * from '../pages/Cart/Cart.module';
export * from '../pages/Catalog/Catalog.module';
export * from '../pages/Main/Main.module';
export * from '../pages/NotFound/NotFound.module';
export * from '../pages/LogIn/LogIn.module';
export * from '../pages/SignUp/SignUp.module';
export * from './AccountActivation/AccountActivationPage';
export * from '../pages/GoodDetails/GoodDetails';
export * from '../pages/Checkout/Checkout';
export * from '../pages/Reset/Reset.module';
export * from '../pages/Reset/Confirm.module';
export * from '../pages/SuccessOrder/SuccessOrder';
export * from '../pages/Info/WarningList';
export * from '../pages/Info/Delivery';
export * from '../pages/Info/Contacts';
export * from '../pages/Info/FAQs';
